services:
  web:
    container_name: kigwiki-site
    build: ./
    ports:
      - "3100:3000"
    volumes:
      - ./:/app
      - ../docs:/app/docs
      - ../makers:/app/makers  
      - ../hadatai:/app/hadatai
      - ../static:/app/static
      - /app/node_modules
      - /app/.docusaurus
    environment:
      - NODE_ENV=development
    command: npm run start -- --host 0.0.0.0